image: ubuntu:20.04

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  script:
    - apt-get update
    - apt-get install -y build-essential automake gcc-multilib
    - ./autogen.sh
    - CFLAGS=-g ./configure --prefix=$PWD/install
    - make install
  artifacts:
    paths:
      - install/

test:
  stage: test
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get install -y build-essential python3 gdb gcc-multilib libc6-dbg
    - cd none/diff_tests && python3 run_tests.py
