image: debian:11.3

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  script:
    - apt-get update
    - apt-get install -y build-essential binutils automake gcc-multilib python3 gfortran
    - cd derivgrind && python3 gen_replace_math.py && python3 gen_dot_operations.py dot > dg_dot_operations.c && python3 gen_dot_operations.py bar > dg_bar_operations.c && cd -
    - ./autogen.sh
    - CFLAGS=-g ./configure --prefix=$PWD/install
    - make install
  artifacts:
    paths:
      - install/

test_x86:
  stage: test
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get install -y build-essential gfortran gdb gcc-multilib g++-multilib gfortran-multilib libc6-dbg git clang libomp-dev
    - dpkg --add-architecture i386
    - apt-get update
    - apt-get install -y python3:i386 python3-numpy:i386 python3-dev:i386
    - cd derivgrind/diff_tests && ./setup.sh && cd - 
    - cd derivgrind/diff_tests && python3 run_tests.py x86*

.test_amd64:
  stage: test
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get install -y build-essential gfortran python3 python3-numpy python3-dev gdb gcc-multilib g++-multilib gfortran-multilib libc6-dbg git clang libomp-dev
    - cd derivgrind/diff_tests && ./setup.sh && cd - 
    - cd derivgrind/diff_tests && python3 run_tests.py amd64*
