image: ubuntu:20.04

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  script:
    - apt-get update
    - apt-get install -y build-essential binutils automake gcc-multilib python3
    - ./autogen.sh
    - CFLAGS=-g ./configure --prefix=$PWD/install
    - make install
    - cd none/libm-extension && python3 compile.py && cd -
  artifacts:
    paths:
      - install/
      - none/libm-extension/lib32/libmextension.so
      - none/libm-extension/lib32/libmoriginal.so
      - none/libm-extension/lib64/libmextension.so
      - none/libm-extension/lib64/libmoriginal.so

test:
  stage: test
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get install -y build-essential python3 python3-numpy gdb gcc-multilib g++-multilib gfortran-multilib libc6-dbg
    - export DG_CONSTRAINED_ENVIRONMENT=1
    - cd none/diff_tests && python3 run_tests.py
