image: debian:11.3

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  script:
    - apt-get update
    - apt-get install -y build-essential binutils gfortran automake gcc-multilib g++-multilib python3 python3-dev
    - ./autogen.sh
    - CFLAGS=-g ./configure --prefix=$PWD/install --enable-fortran --enable-python
    - make install
  artifacts:
    paths:
      - install/

test_dot_x86:
  stage: test
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get install -y build-essential gfortran gdb gcc-multilib g++-multilib gfortran-multilib libc6-dbg clang libomp-dev python3 python3-numpy
#    - dpkg --add-architecture i386
#    - apt-get update
#    - apt-get install -y python3:i386 python3-numpy:i386 python3-dev:i386
    - cd derivgrind/diff_tests && python3 run_tests.py dot_x86*

test_bar_x86:
  stage: test
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get install -y build-essential gfortran gdb gcc-multilib g++-multilib gfortran-multilib libc6-dbg clang libomp-dev python3 python3-numpy
#    - dpkg --add-architecture i386
#    - apt-get update
#    - apt-get install -y python3:i386 python3-numpy:i386 python3-dev:i386
    - cd derivgrind/diff_tests && python3 run_tests.py bar_x86*

.test_dot_amd64:
  stage: test
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get install -y build-essential gfortran python3 python3-numpy python3-dev gdb gcc-multilib g++-multilib gfortran-multilib libc6-dbg git clang libomp-dev
    - cd derivgrind/diff_tests && ./setup.sh && cd - 
    - cd derivgrind/diff_tests && python3 run_tests.py dot_amd64*

.test_bar_amd64:
  stage: test
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get install -y build-essential gfortran python3 python3-numpy python3-dev gdb gcc-multilib g++-multilib gfortran-multilib libc6-dbg git clang libomp-dev
    - cd derivgrind/diff_tests && ./setup.sh && cd - 
    - cd derivgrind/diff_tests && python3 run_tests.py bar_amd64*
