/*--------------------------------------------------------------------*/
/*--- Handling of min/max operations.             dg_dot_minmax.c ---*/
/*--------------------------------------------------------------------*/

/*
   This file is part of Derivgrind, a tool performing forward-mode
   algorithmic differentiation of compiled programs implemented
   in the Valgrind framework.

   Copyright (C) 2022 Chair for Scientific Computing (SciComp), TU Kaiserslautern
   Homepage: https://www.scicomp.uni-kl.de
   Contact: Prof. Nicolas R. Gauger (derivgrind@scicomp.uni-kl.de)

   Lead developer: Max Aehle (SciComp, TU Kaiserslautern)

   This program is free software; you can redistribute it and/or
   modify it under the terms of the GNU General Public License as
   published by the Free Software Foundation; either version 2 of the
   License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful, but
   WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, see <http://www.gnu.org/licenses/>.

   The GNU General Public License is contained in the file COPYING.
*/

/*! \file dg_dot_minmax.c
 *  Define functions for forward-mode AD handling of the min and max operations.
 *
 *  These functions are used to define CCalls for the handling of operations
 *  in the file dg_dot_operations.c generated by gen_operationhandling_code.py.
 */

#include "pub_tool_basics.h"

VG_REGPARM(0) ULong dg_dot_arithmetic_min32(ULong x, ULong xd, ULong y, ULong yd){
  if( *(double*)&x < *(double*)&y ) return xd;
  else return yd;
}
VG_REGPARM(0) ULong dg_dot_arithmetic_min64(ULong x, ULong xd, ULong y, ULong yd){
  if( *(float*)&x < *(float*)&y ) return xd;
  else return yd;
}
VG_REGPARM(0) ULong dg_dot_arithmetic_max32(ULong x, ULong xd, ULong y, ULong yd){
  if( *(double*)&x > *(double*)&y ) return xd;
  else return yd;
}
VG_REGPARM(0) ULong dg_dot_arithmetic_max64(ULong x, ULong xd, ULong y, ULong yd){
  if( *(float*)&x > *(float*)&y ) return xd;
  else return yd;
}
